---
- name: Enable routing and NAT for WireGuard
  hosts: localhost
  become: true
  vars:
    wg_subnet: "10.0.0.1/24"       # Replace with your WireGuard subnet
    public_interface: "enp3s0"     # Replace with your actual external interface (e.g., enp3s0)

  tasks:

    - name: Enable IP forwarding at runtime
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Ensure net.ipv4.ip_forward is persistent
      lineinfile:
        path: /etc/sysctl.conf
        regexp: '^net.ipv4.ip_forward='
        line: 'net.ipv4.ip_forward=1'

    - name: Allow forwarding in UFW
      replace:
        path: /etc/default/ufw
        regexp: '^DEFAULT_FORWARD_POLICY=.*'
        replace: 'DEFAULT_FORWARD_POLICY="ACCEPT"'

    - name: Insert NAT rules properly in before.rules
      blockinfile:
        path: /etc/ufw/before.rules
        marker: "# {mark} ANSIBLE MANAGED BLOCK - WireGuard NAT"
        insertbefore: '^\*filter'
        block: |
          *nat
          :POSTROUTING ACCEPT [0:0]
          -A POSTROUTING -s {{ wg_subnet }} -o {{ public_interface }} -j MASQUERADE
          COMMIT
      become: true

    - name: Ensure UFW is enabled
      ufw:
        state: enabled

    - name: Reload UFW to apply changes
      command: ufw reload

